// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW8jcDw3g9NHj_5sOLsBeGXgvrmDyPMZ0',
    appId: '1:864309675440:web:f5daa9342668dcc69ec275',
    messagingSenderId: '864309675440',
    projectId: 'lexi-app-utem',
    authDomain: 'lexi-app-utem.firebaseapp.com',
    storageBucket: 'lexi-app-utem.firebasestorage.app',
    measurementId: 'G-YZCH3D36MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAubNTLVHY9wV4hyQJ_izkfcK7BZHHBA',
    appId: '1:864309675440:android:098c3ff9ff6b0b6c9ec275',
    messagingSenderId: '864309675440',
    projectId: 'lexi-app-utem',
    storageBucket: 'lexi-app-utem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZeHzjBXJXUg9Nz-UA3DYgdfk1MJnv6M',
    appId: '1:864309675440:ios:a40d0e96e259d6bf9ec275',
    messagingSenderId: '864309675440',
    projectId: 'lexi-app-utem',
    storageBucket: 'lexi-app-utem.firebasestorage.app',
    iosBundleId: 'com.example.lexiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZeHzjBXJXUg9Nz-UA3DYgdfk1MJnv6M',
    appId: '1:864309675440:ios:a40d0e96e259d6bf9ec275',
    messagingSenderId: '864309675440',
    projectId: 'lexi-app-utem',
    storageBucket: 'lexi-app-utem.firebasestorage.app',
    iosBundleId: 'com.example.lexiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW8jcDw3g9NHj_5sOLsBeGXgvrmDyPMZ0',
    appId: '1:864309675440:web:50551ba9aa81ad419ec275',
    messagingSenderId: '864309675440',
    projectId: 'lexi-app-utem',
    authDomain: 'lexi-app-utem.firebaseapp.com',
    storageBucket: 'lexi-app-utem.firebasestorage.app',
    measurementId: 'G-7JTSMWRE66',
  );
}
